<?php
namespace app\api\controller;

use app\admin\model\Doctor;
use app\admin\model\Duty;
use app\admin\model\Number;
use app\common\controller\Api;
use fast\Tree;
use think\Collection;

class Department extends Api
{
    protected $model = null;

    protected $noNeedLogin = ['myDepert','doctorlist','doctorall','doctorInfo','number','queueTime'];

    protected $noNeedRight = ['myDepert'];

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model = new \app\admin\model\Department();
        $this->doctorlist = new Doctor();
        $this->number = new Number();
        $this->duty = new Duty();
    }

    public function myDepert(){
        $res =  $this->model->order('id desc')->field('id,pid,name')->select();
        $tree = Tree::instance();
        $tree->init(Collection($res) ->toArray(),'pid');
        $depertlist = $tree->getTreeArray(0);
        $depertdata = [0 => ['id' => '0', 'name' => __('None')]];
        foreach ($depertlist as $k => $v) {
            $depertdata[$v['id']] = $v;
        }
      $this->success('成功',$depertlist);
    }
    //门诊医生
    public function doctorlist(){
        $did = $this->request->get('did');
        $collection = $this->doctorlist->where('did', $did)->select();
        $this->success('成功',$collection);
    }
    //专家医生
    public function doctorall(){
        $doctorData = $this->doctorlist->where('deletetime', 'null')->select();
        $this->success('成功',$doctorData);
    }
    //专家信息
    public function doctorInfo($did){
        $doctorInfo = $this->doctorlist->where('id', $did)->find();
        $this->success('成功',$doctorInfo);
    }
    //排版管理
    public function queueTime(){
        $doctorId = $this->request->get('doctorId');
        $numberlist = $this->duty->where('doctor_id',$doctorId)->select();
        $this->success('成功',$numberlist);
    }
    //号源管理
   public function number(){
        $unmberAll = $this->number->where('status', 'normal')->select();
        $this->success('成功',$unmberAll);
    }
    public function numbertime(){

    }
}

