<?php

namespace app\api\controller;

use app\common\controller\Api;

class Order extends Api
{
    protected $noNeedLogin = ['postOrder'];

    protected $noNeedRight = ['postOrder'];

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //$this->orderModel = new \app\admin\model\Order();
        $this->model = model('\app\admin\model\Order');

    }
    public function postOrder(){
        if ($this->request->isPost()) {
            $dataPost = $this->request->param();
            $dataPost['order_num'] ="NUM" . date('Ymd') . str_pad(mt_rand(1, 99999), 5, '0', STR_PAD_LEFT);
            //var_dump($dataPost);die();

           /* $save = $this->model->allowField(true)->save($dataPost);
            if ($save) {
                $this->success('下单成功');
            }*/

            $this->success('下单成功');
        }




    }

}